---
driver:
  name: ec2
  aws_ssh_key_id: abansal
  associate_public_ip: true
  availability_zone: us-east-1a 
  instance_type: m3.medium
  security_group_ids: ['sg-bbb2a4dc']
  region: us-east-1
  subnet_id: subnet-6c84a535
  iam_profile_name: chef-openvpn-role

transport:
  ssh_key: ~/test.pem  

provisioner:
  name: chef_zero
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/data_bags/encrypted_data_bag_secret


platforms:
  - name: ubuntu-12.04

suites:
  - name: files
    run_list:
      - recipe[prep::default]
      - recipe[opsline-openvpn]
    attributes:
      opsline-openvpn:
        users:
          s3bucket: 'chef-openvpn-testing'
  - name: openvpn
    run_list:
      - recipe[opsline-openvpn]
    provisioner:
      name: chef_zero
      data_bags_path: test/integration/empty_data_bags
      encrypted_data_bag_secret_key_path: test/integration/data_bags/encrypted_data_bag_secret
  - name: duo
    run_list:
      - recipe[prep::default]
      - recipe[opsline-openvpn]
    attributes:
      opsline-openvpn:
        mfa:
          enabled: true
  - name: persistence
    run_list:
      - recipe[prep::default]
      - recipe[opsline-openvpn]
    attributes:
      opsline-openvpn:
        users:
          s3bucket: 'chef-openvpn-testing'
  - name: user_removal
    run_list:
      - recipe[prep::default]
      - recipe[prep::users]
      - recipe[opsline-openvpn]