name             'opsline-openvpn'
maintainer       'OpsLine'
maintainer_email 'team@opsline.com'
license          'All rights reserved'
description      'Installs/Configures opsline-openvpn'
long_description 'Installs/Configures opsline-openvpn'
version          '0.1.2'

depends 'iptables'
depends 'openvpn', '>= 2.1.1'
depends 'route53'
